name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.16.x'

    - name: Install static analysis tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install golang.org/x/lint/golint@latest
        go install honnef.co/go/tools/cmd/staticcheck@v0.2.2
        go install github.com/securego/gosec/v2/cmd/gosec@v2.9.1

    - name: Vet
      run: go vet ./...

    - name: Goimports
      run: test -z $(goimports -e -d . | tee /dev/stderr)

    - name: Gocyclo
      run: gocyclo -over 20 .

    - name: Golint
      run: golint -set_exit_status $(go list ./...)

    - name: Staticcheck
      run: staticcheck -go 1.16 ./...

    - name: Gosec
      run: gosec ./...